### ISSUE TITLE
Check file extension suppoort

### ISSUE THREAD

**Issue by rafaelcastrocouto** [vagnervjs/player.io#1]
O programa deveria verificar se o arquivo é suportado e avisar ao usuário

**Comment by vagnervjs** [comment]
Então, isso é feito: 
![Captura de Tela 2013-03-17 a s 12 24 45](https://f.cloud.github.com/assets/1696024/268223/e4d54210-8f16-11e2-9577-a75583b7a1a5.png)

Talvez o problema pode ser em algum específico, poderia me dizer qual tipo de arquivo?

**Comment by rafaelcastrocouto** [comment]
nos arquivos tipo mp4 ou ogg ... dependendo da codificação não toca ...
talvez algo do tipo:
media.canPlayType(type)
onde o tipo seja "deduzido" através da extensão

**Comment by vagnervjs** [comment]
É exatamente isso que faço, o problema é quando o navegador suporta o arquivo, mas não suporta reproduzir blobs urls. Por exemplo o Safari que apesar de suportar mp4, não suporta reproduzir blobs urls. Se você testar no Chrome ou Firefox o arquivo vai rodar.

**Comment by rafaelcastrocouto** [comment]
Estou no chrome ... vou fazer um fork e tentar buscar uma forma de saber se o arquivo vai ser reproduzido ... talvez verificar o comprimento da faixa...

**Comment by vagnervjs** [comment]
Problema resolvido a partir do fork do @rafaelcastrocouto
