### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by kevkha** [vagnervjs/player.io#4]
Hello Vagner,

I like your concepts and thanks for sharing your work. I tried your demo but getting below error in debug. I downloaded the code and run it locally but still getting the same. Can you take a look and suggest what might be the cause? Thanks in advance.

<pre>
Failed to load resource: net::ERR_CONNECTION_REFUSED
</pre>

**Comment by vagnervjs** [comment]
Hi @kevkha, 
Thanks for you feedback.
This error occurs when the service is not started. 
The command `node app.js` should resolve. 

At this moment, I can't access my server to restart the service, or test it locally, but I'll try again later. 
Make sure you start the service and try again, and tell me if works or not.

Thanks

**Comment by kevkha** [comment]
Hi Vagner,

Thanks for your prompted response. I ensured the service is started

<pre>
\player.io>node app.js
   info  - socket.io started
Server started at http://localhost:8080
</pre>

I also made the change in <code>client.js</code> and <code>all.min.js</code> in my setup but it didn't work.

<code>
var socket = io.connect('http://localhost:8080');
</code>

I will wait for your next update after you have looked at your environment. Thanks.

**Comment by kevkha** [comment]
<b>Update:</b> I cleared the previous error by removing the <code>.com</code> that I left out in <code>all.min.js</code> caused by me.

The new issue I face now is when I connect to the client  via QR code to my localhost it crashed the app.js

<pre>
   debug - got heartbeat packet
   debug - cleared heartbeat timeout for client 8vR4C_Crq_MrqoUs2gSL
   debug - set heartbeat interval for client 8vR4C_Crq_MrqoUs2gSL
ugmzZ
C:\player.io\app.js:28
        sockets[id].emit('play', {action:'playlist'});
                   ^
TypeError: Cannot read property 'emit' of undefined
    at null._onTimeout (C:\player.io\app.js:28:20)
    at Timer.listOnTimeout (timers.js:110:15)
</pre>

**Comment by kevkha** [comment]
It's all well now. I needed to update <code>mobile.jade</code> to match with my local setup.

**Comment by vagnervjs** [comment]
Great @kevkha =D
