### ISSUE TITLE
Player.io with NW.js

### ISSUE THREAD

**Issue by kevkha** [vagnervjs/player.io#5]
Hi Vagner,

I really like your player.io. It works very well as long as we don't attempt to initiate another instance of localhost:8080 on another device and kick off another client. This would crash <code>node app.js</code> 

I would like to implement Player.io into NW.js desktop app. Have you tried it before? Will socket.io server work in NW.app as front end and still able to control the media player from smartphone?

**Comment by vagnervjs** [comment]
Hi @kevkha,

I believe that Player.io front-end will works ok with NW.js, since NW.js has the same behaviour of browsers.
In my test I have no problem with multiple clients connected simultaneously. In my server I run the app as a daemon using [forever](https://www.npmjs.com/package/forever), I encourage you to try that.

**Comment by vagnervjs** [comment]
About run player.io server in NW.js I never try, but I think if NW.js works ok with socket.io, it'll works ok with player.io too :)

**Comment by kevkha** [comment]
Hi Vagner, I have no problems with multiple clients connecting to the same instance of server front end. Here, I refer to multiple instances of the server front ends like open first browser and point to http://localhost:8080 and connect multiple clients here fine, and then open second browser and point to the same http://localhost:8080 and open clients to send command would crash.

Also, I learn that NW.js does not support HTML5 Video Player out of the box. Need to add it manually per https://github.com/mllrsohn/grunt-node-webkit-builder/wiki/How-to-automate-node-webkit-support-for-MP3-&-H264-in-video-&-audio-tags-with-grunt-contrib-copy. I will give it a shot. Thanks.
